package com.example.demo.entity;

public enum NotificationType {
    LOW_STOCK, PENDING_JOB, DAMAGED_ITEM, INVOICE_CREATED, JOB_CANCELLED, STOCK_UPDATE, ITEM_REMOVED, INVOICE_DELETED, JOB_UPDATED, DELIVERED, PAYMENT_RECEIVED, JOB_STATUS_CHANGED, JOB_COMPLETED
}