package com.example.demo.entity;

public enum NotificationType {
    LOW_STOCK, PENDING_JOB, DAMAGED_ITEM, INVOICE_CREATED, JOB_CANCELLED, STOCK_UPDATE, ITEM_REMOVED, INVOICE_DELETED, JOB_UPDATED, DELIVERED, PAYMENT_RECEIVED, JOB_STATUS_CHANGED, INVOICE_RETURNED, JOB_COMPLETED , EXPENSES_UPDATE , FAULT_UPDATE , BRAND_UPDATE,MODEL_UPDATE,MODELNUM_UPDATE,SERVICE_UPDATE,PROCESSOR_UPDATE, DEVICECONDITON_UPDATE
}